"""init

Revision ID: e258bd706360
Revises: 
Create Date: 2026-06-11 09:44:07.440353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e258bd706360'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('invoice',
    sa.Column('invoice_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('shipping', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    op.create_index('idx_invoice_user_id', 'invoice', ['user_id'], unique=False)
    op.create_table('item',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), server_default='1.00', nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('savings', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.invoice_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index('idx_item_invoice_id', 'item', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_item_invoice_id', table_name='item')
    op.drop_table('item')
    op.drop_index('idx_invoice_user_id', table_name='invoice')
    op.drop_table('invoice')
    op.drop_table('user')
    # ### end Alembic commands ###
